modLoader = "javafml"
loaderVersion = "[47,)"
license = "Custom"

[[mods]]
modId = "advanceweather"
version = "1.0-beta"
displayName = "Advance Weather"
authors = "Gamerofpro"
description = '''
This mod makes weather more accurate than vanilla weather system.
More features will be added soon.
'''

[[dependencies.advanceweather]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.advanceweather]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
